# site properties and page defaults
title: TRIO Lab
subtitle: Trustworthy Robotics, Intelligence, and Optimization Lab
description: A research lab at Carnegie Mellon University focused on trustworthy robotics, intelligence, and optimization.
header: images/background-new.png
header-dark: false
footer: images/background-new.png
footer-dark: false
proofer: false

# site social media and other links
links:
  #email: contact@trio-cmu.com
  #orcid: 0000-0001-8713-9213
  # google-scholar: ETJoidYAAAAJ
  github: trio-cmu
  #twitter: trio-cmu
  #youtube: trio-cmu

### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
